#ifndef _STATU_H_
#define _STATU_H_

enum SPI_REGISTER {
  REGISTER_FAILE = -1,
  HAS_BEEN_REGISTER = 0,
  REGISTER_SUCCESS = 1,
  SPIMGR_LIST_NULL,
  SPIMGR_INIT_SUCCESS,
  SPIMGR_INIT_NO_FIND,
  SPIMGR_INIT_FAILE,
};

#endif